### ISSUE TITLE
Componente: Showcase

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#135]
![image](https://user-images.githubusercontent.com/22228470/118135527-883e6e00-b3d9-11eb-80e3-18c93d300f09.png)
![image](https://user-images.githubusercontent.com/38676242/118312043-25c39b80-b4c7-11eb-833c-907a61028cde.png)

**Comment by MatheusRaj** [comment]
RFC:

```jsx
import Showcase from '@eduzz/houston-ui/Showcase';

<Showcase size='small' title='Nova forma de enviar os vídeos' textButton='Ok, entendi'>
    <Showcase.Step>
         <img src='https://pbs.twimg.com/profile_images/1333265151118729218/ciPb4yEY_400x400.jpg'>

         <p>
              Agora no nutror você pode enviar vídeos de gatinhos e cachorrinhos fofinhos sem se preocupar com pirataria, 
              quem nessa vida faria mal a eles?
          </p>
    </Showcase.Step>
</Showcase>;

<Showcase size='small' title='Nova forma de enviar os vídeos' textButton='Ok, entendi'>
    <Showcase.Step>
         <img src='https://pbs.twimg.com/profile_images/1333265151118729218/ciPb4yEY_400x400.jpg'>

         <p>
              Agora no nutror você pode enviar vídeos de gatinhos e cachorrinhos fofinhos sem se preocupar com pirataria, 
              quem nessa vida faria mal a eles?
          </p>
    </Showcase.Step>
    <Showcase.Step>
         <img src='https://pbs.twimg.com/profile_images/1333265151118729218/ciPb4yEY_400x400.jpg'>

         <p>
              Agora no nutror você pode enviar vídeos de gatinhos e cachorrinhos fofinhos sem se preocupar com pirataria, 
              quem nessa vida faria mal a eles?
          </p>
    </Showcase.Step>
</Showcase>;
```

### Showcase props available

| prop           | type                | required | default    | description |
| -------------- | ------------------- | -------- | ---------- | ----------- |
| id             | `string`            | `false`  | -          |             |
| className      | `string`            | `false`  | -          | -           |
| size           | `'small, medium ou large'` | `false`  | `'medium'` | -           |
| textButton           | `string` | `false`  | `'Ok, entendi'` | -           |

**Comment by ffernandomoraes** [comment]
Sugestão:

Ao invés de usar a tag IMG, usa Showcase.Image, o texto Showcase.Text, o titulo Showcase.Title, o botão Showbase.Button... Assim não corremos o risco de usarem de forma errada/despadronizada.

**Comment by ffernandomoraes** [comment]
Qual a dimensão ideal da imagem? Poderia deixar como descrição do componente.

**Comment by MatheusRaj** [comment]
Editado bro!

**Comment by ffernandomoraes** [comment]
Ainda acho que não faz sentido ter a prop title e textButton, poderiam seguir o mesmo padrão. Component.SubComponent. O que acha?

**Comment by MatheusRaj** [comment]
Acho que faz sentido usar subcomponentes quando pode acontecer alguma alteração genérica, exemplo: Todas as imagens precisam de um lazy load, nesse caso é interessante usar um Showcase.Image.

No caso do title e textButton, no caso do componente Showcase do Houston, não será alterável para não perder o propósito do componente.

**Comment by MatheusRaj** [comment]
Concordo, pra manter o padrão de projeto. Editado!
