### ISSUE TITLE
Performance da Tabela

### ISSUE THREAD

**Issue by miguelaugl** [eduzz/houston#137]
Implementarei a prop virtualized para a tabela para lidarmos com volumes grandes de dados.
Para isso vou utilizar por baixo dos panos a lib react-virtualized.

**Comment by danieloprado** [comment]
Então mas já fazemos isso na tabela, do que você está precisando?

**Comment by ffernandomoraes** [comment]
Dois pontos ainda:

- O tooltip não funciona bem com muitos dados na tabela (faz travar a tela praticamente).
- Quando há muitas linhas, não ta ficando legal, pesa muito a página, as vezes trava, pelo menos na minha cabeça temos que colocar o virtualized pra ele remover os elementos do DOM quando não está visivel.

**Comment by ffernandomoraes** [comment]
Vai ser feito algo @miguelaugl ?

**Comment by danieloprado** [comment]
Não teria outra solução mais simples? Imagino que teria me mexer bastante na estrutura da tabela para isso

**Comment by miguelaugl** [comment]
Eu consegui resolver o problema de performance da tabela removendo alguns tooltips, essa foi a solução que encontrei pro meu caso, mas acho que seria interesse em algum momento implementarmos um tooltip para ser utilizado em tabelas

**Comment by danieloprado** [comment]
O problema acontece quando é feito o render ou quando ele ja foi feito? se for durante da para mexer nas configurações do useLazyArray

**Comment by danieloprado** [comment]
Vendo aqui, acho que vamos precisar fazer algo melhor mesmo, poderia usar o react-window que é uma versão refeito do react-virtualized do próprio autor. O único porem é necessário saber o height de cada row e isso pode complicar o responsivo. Talvez uma solução por hora é diminuir no Órbita para no máximo 50 ou 30 linhas por página.

**Comment by ffernandomoraes** [comment]
Realmente o mobile não sei como iria funcionar.

Se nós implementarmos o react-window resolve o problema dos tooltip`s ?

**Comment by danieloprado** [comment]
Acho que não, talvez tenhamos que melhorar o tooltip para não virar um render em cada novo e sim um global

**Comment by miguelaugl** [comment]
Sim, algo nesse sentido para o tooltip é uma boa também, vou alinhar com o pessoal do Órbita se tudo bem diminuirmos para 50 linhas por página enquanto a gente não aplica o react-window
