### ISSUE TITLE
Componente: Menu

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#146]

**Comment by phelpa** [comment]
RFC:

```jsx
import Menu from '@eduzz/houston-ui/Menu';

const handleClick = (event: React.MouseEvent<HTMLButtonElement>) => {
  setAnchorEl(event.currentTarget);
};

const handleClose = () => {
  setAnchorEl(null);
};

<>
  <Button onClick={handleClick}>
    Open Menu
  </Button>
  <Menu
    anchorEl={anchorEl}
    open={Boolean(anchorEl)}
    onClose={handleClose}
  >
  <Menu.Item onClick={handleClose}>Item 1</Menu.Item>
  <Menu.Item>Item 2</Menu.Item>
  <Menu.Item>Item 3</Menu.Item>
  </Menu>;
</>
```

### Menu props available

| prop           | type                | required | default    | description |
| -------------- | ------------------- | -------- | ---------- | ----------- |
| id             | `string`            | `false`  | -          |             |
| className      | `string`            | `false`  | -          | -           |
| anchorEl           | `HTML element` | `true`  | ` -` |  Elemento HTML onde o menu vai ficar ancorado        |
| children           | `node` | `true`  | ` -` |  <Menu.Item/>       |
| onClose           | `function` | `false`  | ` -` |  function(event: object, reason: string) => void       |
| open           | `boolean` | `true`  | ` -` |  Se true o menu fica aberto      |


### Menu.Item props available

| prop           | type                | required | default    | description |
| -------------- | ------------------- | -------- | ---------- | ----------- |
| id             | `string`            | `false`  | -          |             |
| className      | `string`            | `false`  | -          | -           |
| onClick      | `function`            | `false`  | -          | onClick: function(event: object) => void         |
| icon      | `node`            | `false`  | -          | Ícone que vai ficar no lado esquerdo do menu.item         ​|

**Comment by ffernandomoraes** [comment]
Vendo aqui, sugiro que tenha `startIcon` e `endIcon`, semelhante o padrão dos outros componentes.

**Comment by ffernandomoraes** [comment]
e ai @phelpa ?
