### ISSUE TITLE
[BUG] Toast duplicado

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#171]

**Comment by MatheusRaj** [comment]
O toast fica duplicado por que a sintaxe da documentação exige que sejam chamados dois ThemeProviders na mesma página.
![image](https://user-images.githubusercontent.com/38676242/124635548-f180b180-de5d-11eb-8a7b-5918073a2d20.png)

Cada ThemeProvider possui um ToastContainer, dessa forma duplicando a chamada dos toasts
![image](https://user-images.githubusercontent.com/38676242/124635731-212fb980-de5e-11eb-91f1-367c8a884d42.png)

Porém em um projeto onde só um ThemeProvider do Houston é chamado no componente pai, esse bug não acontece.
