### ISSUE TITLE
Componente: Table - Labels não definidas no mobile

### ISSUE THREAD

**Issue by gustavodaltoe** [eduzz/houston#187]
Ao criar uma Table comum, não está adicionando as labels no mobile.

Dentro do `<span>` onde deveria estar a label não há nada, mas quando adiciono qualquer texto dentro dele pelo console, aí todas as labels aparecem devido ao observer.

Debugando o código percebi que o observer não é chamado uma primeira vez quando a tabela inicia, apenas quando há uma mutação, o que aparentemente não ocorre na minha table.

**Comment by ffernandomoraes** [comment]
E aí @gustavodaltoe, vou verificar.

**Comment by gustavodaltoe** [comment]
Consegui no playground fazer uma simulação básica do problema:

```
import React, { memo } from 'react';

import faker from 'faker';

import Table from '@eduzz/houston-ui/Table';

const TestTable = () => {
  const rows = new Array(5).fill('a').map((_, index) => ({
    id: index + 1,
    name: `${faker.name.firstName()} ${faker.name.lastName()}`,
    email: faker.internet.email().toLowerCase(),
    price: faker.commerce.price()
  }));

  return (
    <Table stripedRows>
      <Table.Header>
        <Table.Column width={50} sortableField='id'>
          #
        </Table.Column>
        <Table.Column sortableField='name'>Nome</Table.Column>
        <Table.Column sortableField='email'>Email</Table.Column>
        <Table.Column align='right'>Valor</Table.Column>
      </Table.Header>
      <Table.Body>
        <Table.Empty count={rows.length} />
        {rows.map((row, index) => (
          <Table.Row data={row} index={index} key={row.id}>
            <Table.Cell mobileSize={1}>{row.id}.</Table.Cell>
            <Table.Cell mobileSize={11}>{row.name}</Table.Cell>
            <Table.Cell mobileSize={6}>{row.email}</Table.Cell>
            <Table.Cell mobileSize={6} align='right'>
              {row.price}
            </Table.Cell>
          </Table.Row>
        ))}
      </Table.Body>
    </Table>
  );
};

const ComponentsDev = memo(() => {
  return (
    <>
      <TestTable />
    </>
  );
});

export default ComponentsDev;
```

![image](https://user-images.githubusercontent.com/37204510/127390024-b1a3d057-da7c-4991-a26c-3a936525ea3c.png)

Basicamente o erro ocorre quando **não temos** um `<Table.Collapse>`, `<Table.Actions>` ou `<Table.Pagination>`. Isso provavelmente ocorre porque eles forçam que a Mutation seja executada, então percebi que só de forçar uma primeira execução do código da mutation resolve o problema.

**Comment by ffernandomoraes** [comment]
Boa, mesclado @gustavodaltoe. Obrigado pela contribuição.

Versão 0.29.1 foi resolvido.
