### ISSUE TITLE
Linters: ESLint + SonarLint

### ISSUE THREAD

**Issue by LcsCefali** [eduzz/houston#195]
Adicionar as regras recomendadas pelo SonarLint no ESLint do Houston.

Lib: https://github.com/SonarSource/eslint-plugin-sonarjs já faz essa mesclagem das regras.

A intenção é deixar o Lint do Houston mais completo, conseguir reduzir a complexidade do código, aumentar a qualidade/segurança e deixar mais padronizado. Vai ajudar muito os projetos que utilizam o SonarQube, por que conseguimos mexer em possíveis erros (graves ou não) no momento da escrita do código.

**Comment by LcsCefali** [comment]
Adicionado o plugin e resolvido alguns problemas que o SonarLint apontou.

Configurações usadas:
```js
rules: {
  'sonarjs/cognitive-complexity': ['warn', 45],
  'sonarjs/no-duplicate-string': 'off',
},
overrides: [
  {
    'files': ['*.mdx'],
    'rules': {
      'sonarjs/no-identical-functions': 'off'
    }
  }
]
```

Foi necessário esse override por conta dos arquivos .mdx possuírem partes do código repetidas.

Sobre `sonarjs/cognitive-complexity` a ideia seria deixar esse valor por enquanto por ser mais complicado de arrumar, demanda tempo e cuidado. Com o tempo podemos ir arrumando e abaixando esse valor.

**Comment by ffernandomoraes** [comment]
Implementado! Valeu.
