### ISSUE TITLE
[Melhoria] Inserir prop onClick nos componentes.

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#221]
Verificar qual são os componentes que precisam ter esse comportamento, por exemplo: Typography, etc..

**Comment by miguelaugl** [comment]
Fala aí, Fer, dei uma olhada aqui acho que esses componentes seriam interessantes ter:

- Avatar
- Typography

**Comment by ffernandomoraes** [comment]
Valeu Miguel

**Comment by ffernandomoraes** [comment]
Resolvido.
