### ISSUE TITLE
[Melhoria] TableCollapse, componentes para padronizar o visual das tabelas.

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#222]
Precisamos criar alguns componentes para padronizar o visual das Table.Collapse.

![image](https://user-images.githubusercontent.com/22228470/131164657-4c3322fa-d91d-4e9e-a17f-c8cf984106ff.png)

**Comment by ffernandomoraes** [comment]
Olá, preciso de opiniões. No meu ver, há duas maneiras de fazer essa issue. Se alguém tiver outra sugestão, por favor comente.

A primeira opção, seria controlar os estilos passando uma prop para os componentes (<Table.Header isCollapse />, <Table.Column isCollapse />...). Com isso, seria necessário implementar algumas condições no código. (Não gosto dessa opção)

A segunda opção, seria criar novos componentes (Table.CollapseHeader, Table.CollapseColumn...) para controlar esses casos. Assim separando a lógica e os estilos.

_Lembrando que a Table.Collapse não possui todas as funcionalidade da tabela normal e alguns componentes possuem o estilo diferente._

**Comment by caferrari** [comment]
não daria para criar um contexto na <Table.Column> e, ao inserir uma table collapse dentro ela notificar a column e ela já fazer o controle? a notificação do status de "open"/"closed" da TableCollapse fica sendo controlada por esse contexto dai.

**Comment by danieloprado** [comment]
Poderia ser como o carlos falou, o Table.Collpase cria um contexto, e se uma table for criada la dentro ele já usa esse contexto.

**Comment by ffernandomoraes** [comment]
Hm, não entendi muito bem @caferrari . Hoje a implementação está assim:

```
<Table>
  <Table.Head>
    <Table.Column ... />
  </Table.Head>

  <Table.Body>
    <Table.Row>
      <Table.Cell>xpto</Table.Cell>
      <Table.Cell>xpto</Table.Cell>
      <Table.Cell>xpto</Table.Cell>

      <Table.Collapse>
        content
      </Table.Collapse>
    </Table.Row>
  </Table.Body>
</Table>
```

Por que eu criaria um contexto na coluna? E se realmente fosse pra criar um contexto na coluna, em questão de performance seria o ideal? Tendo em vista que já temos um contexto para a tabela e outro para cada linha.

@danieloprado mas e as questões dos estilos? Teríamos que fazer algumas condições no código, ficaria legal?

**Comment by danieloprado** [comment]
```jsx
<Table>
  <Table.Head>
    <Table.Column ... />
  </Table.Head>

  <Table.Body>
    <Table.Row>
      <Table.Cell>xpto</Table.Cell>
      <Table.Cell>xpto</Table.Cell>
      <Table.Cell>xpto</Table.Cell>

      <Table.Collapse>
          <Table>
            <Table.Head>
                <Table.Column ... />
              </Table.Head>
            
              <Table.Body>
                <Table.Row>
                  <Table.Cell>xpto</Table.Cell>
                  <Table.Cell>xpto</Table.Cell>
                  <Table.Cell>xpto</Table.Cell>
                </Table.Row>
              </Table.Body>
         </Table>
      </Table.Collapse>
    </Table.Row>
  </Table.Body>
</Table>
```
Poderia ser um context no Collapse para limitar alguma funcionalidade, ou até não deixar colocar outro collapse dentro, e os estilos daria para trabalhar só com o css mesmo.

**Comment by ffernandomoraes** [comment]
Legal, vou seguir assim, faz sentido. Valeu @caferrari e @danieloprado .

**Comment by JonathasRodrigues** [comment]
lembrando que seria legal ele aceitar qualquer tipo de React.Node, para ficar facil a customização do conteúdo dentro do collapse

**Comment by ffernandomoraes** [comment]
E aí @JonathasRodrigues , está aceitando qualquer conteúdo, essa task é para padronizar quando houver uma tabela dentro do collapse (seguindo a documentação do design). Valeu.
