### ISSUE TITLE
Componente: Password

### ISSUE THREAD

**Issue by danieloprado** [eduzz/houston#27]
Necessário criar um com componente de PasswordField, ele deverá ser igual o TextField mas com a opção de mostrar e aparecer a senha.

[Figma](https://www.figma.com/file/Z1MocTqXbRPGdaHMM9t4Zv/Houston-Design-System?node-id=524%3A466)

**Preview**
![Preview](https://user-images.githubusercontent.com/7683575/110827783-2b0d2b80-8275-11eb-90e1-5dfe7b24e36b.png)

**Comment by danieloprado** [comment]
teste

**Comment by micheleambrosio** [comment]
**RFC**

Pensei em criar um componente semelhante ao componente `TextField`, porém, com menos opções de propriedades, tendo apenas, estendendo:

```jsx
 type FieldTextPropsExtends =
  | 'id'
  | 'label'
  | 'name'
  | 'disabled'
  | 'placeholder'
  | 'fullWidth'
  | 'helperText'
  | 'className'
  | 'value'
  | 'iconType';
```

### Importação e uso
```jsx
import PasswordField from '@eduzz/houston-ui/Forms/PasswordField';

const [password, setPassword] = React.useState('');

<PasswordField label='Senha' value={password} onChange={setPassword} />
```

E, dentro do componente `PasswordField`, é controlado se a senha deve ser exibida ou não, mudando seu `type` de password para text ao clicar no ícone.

Em `iconType` pode-se escolher entre dois tipos de ícones: `filled` e `outlined`.

### Propriedades

| prop         | tipo                        | obrigatório | padrão  | descrição                                                                          |
| ------------ | --------------------------- | ----------- | ------- | ---------------------------------------------------------------------------------- |
| id           | `string`                    | `false`     | -       |                                                                                    |
| name         | `string`                    | `true`      | -       |                                                                                    |
| label        | `React.ReactNode`           | `false`     | -       |                                                                                    |
| placeholder  | `string`                    | `false`     | -       |                                                                                    |
| disabled     | `boolean`                   | `false`     | `false` |                                                                                    |
| fullWidth    | `boolean`                   | `false`     | `false` |                                                                                    |
| className    | `string`                    | `false`     | -       |                                                                                    |
| helperText   | `string`                    | `false`     | -       | Exibe texto de ajuda abaixo do componente de senha                                 |
| errorMessage | `string`                    | `false`     | -       | Exibe uma mensagem de erro no componente de senha, assim como indica erro no campo |
| form         | `IFormAdapter`              | `false`     | -       |                                                                                    |
| value        | `any`                       | `false`     | -       |                                                                                    |
| margin       | `none`, `dense`, `normal`   | `normal`    | -       |                                                                                    |
| onChange     | `function`                  | `false`     | -       | Função disparada ao alterar o valor do campo de senha                              |
| onBlur       | `function`                  | `false`     | -       | Função disparada ao tirar o foco do componente                                     |

**Comment by danieloprado** [comment]
acredito que pode tirar o _iconType_ pois a idéia é seguir o padrão do houston. Imagino que esse componente pode ser um "superset" do TextField.

**Comment by micheleambrosio** [comment]
> acredito que pode tirar o _iconType_ pois a idéia é seguir o padrão do houston. Imagino que esse componente pode ser um "superset" do TextField.

Nos ícones do Figma do Houston, temos os 2 tipos de ícones. Isso vai ser setado no ThemeProvider ou algo do tipo? Se não, qual vai ser o padrão?

**Comment by danieloprado** [comment]
Imagino que deva ficar no tema mesmo, mas como ainda não temos um componente fechado de icon, pode deixar sem essa opção e pegar o icone do mdi

**Comment by ffernandomoraes** [comment]
Não rola de criar uma interface base genérica para o `TextField`, `PasswordField` e `SearchField` (está em backlog)? Tendo em vista que há muita semelhança entre as props deles.

**Comment by danieloprado** [comment]
Acredito que podemos usar o ITextFieldProps como base e estender delas os outros, é possível usar o Omit para tirar alguma prop que não queria passar.

**Comment by ffernandomoraes** [comment]
Sim, algo nesse nível... Se um dia precisar alterar/atualizar mexemos apenas em uma interface. Boa!

**Comment by danieloprado** [comment]
@micheleambrosio blz?

**Comment by micheleambrosio** [comment]
Acredito que os campos que são mais comuns para o `TextField` e não para os outros seja apenas: `type`, `multiline`, `loading` e `mask`.

Então, vou referenciar a interface `ITextFieldProps` e usar o Omit dos campos acima, pode ser?
