### ISSUE TITLE
Resolver as opções por páginas com base no total de itens na lista

### ISSUE THREAD

**Issue by chriscorrales** [eduzz/houston#298]
Estava testando o componente de tabela e percebi um detalhe. Vou dar exemplo para explicar melhor:
Eu setei na props optionsPerPage=[10, 20, 30, 40]  essas opções e vamos supor que o meu total de itens no meu array é 25, faz sentido exibir a opção 40 já que a opção de 30 já vai exibir todos os itens desse array? Gostaria de ver o que vocês acham. Se faz sentido resolver isso no Houston, ou quem implementa o Houston deve tratar isso? Ou nem precisa tratar isso?
![image](https://user-images.githubusercontent.com/25913385/164324738-b67ddd58-1123-41a1-88fd-0f506ed10fac.png)
![image](https://user-images.githubusercontent.com/25913385/164324848-ab62fbf7-a02b-4022-b2cd-e338aca2cdbc.png)
![image](https://user-images.githubusercontent.com/25913385/164322510-474520af-4f7f-470b-aca2-e9ab0b742ee4.png)

**Comment by miguelaugl** [comment]
E aí, mano, de boas?

Mano, eu não acho que seja um grande problema exibir a opção que estrapolam o número de itens e vejo dois problemas em a gente fazer essa tratativa:

> O primeiro é que se fizer dentro do Houston vai ser um cálculo a mais sem muito ganho no componente, saca?
> O outro ponto que vejo é que talvez fique meio confuso pro usuário, ele vai ter que reconhecer que dependendo da quantidade de itens vai ser mais ou menos opções, acho que geraria complexidade

O que acha?

**Comment by ffernandomoraes** [comment]
Fala Cris, primeiro gostaria de agradecer sua contribuição ❤️.

Segundo, eu fico um pouco preocupado com esse tipo de ajuste. De certa forma não traz muito valor para o componente (não impacta muito o uso), gera complexibilidade a toa (mesmo sendo pouca) e pode gerar dúvidas para nossos usuários conforme citado pelo Miguel.

E ao meu ver opções padronizadas ([10, 20, 30, 40]) por toda a aplicação fazem mais sentido do opções dinâmicas ([10, 20, 30]).

Outro ponto, quando o total de itens for menor do que 10, só vai aparecer uma única opção ([10])? Não ficaria um pouco estranho? Ou deveríamos sumir com o Select?

Mas tudo o que eu falei é minha opinião, ainda estou aberto a discussões. Se quiser, chamo um designer para nos dar uma opinião também. O que acha?

**Comment by chriscorrales** [comment]
Gostei do ponto de vocês, por mim é realmente uma dúvida, até não tratar isso é opção e gostaria de decidir isso em conjunto até, antes de sair fazendo algo.
Eu concordo com a opinião de vocês e por mim já está quase certo isso, gostaria de entender um pouco mais só da percepção de usuário, se realmente isso acontece de fato, então sim, acho válido trazer um Design para a discussão @ffernandomoraes.
Obrigado guys, vocês fizeram eu ter outras percepções :)

**Comment by ffernandomoraes** [comment]
Boa, solicitei ajuda para nossos Designers, em breve algum deles devem comentar algo por aqui. Valeu

**Comment by danieloprado** [comment]
Boa, sobre isso não acho legal ficar "sumindo" com opções pois pode gerar uma confusão do usuário procurar uma coisa e não achar por ter uma regra não explicita.

**Comment by Notlim38** [comment]
Oi pessoal! 

Acredito ser bem pertinente o questionamento do @chriscorrales, afinal o usuário não precisa ver aquilo que não vai funcionar.  Logo, se a lista possui 25 itens não precisaria ver o número 40. 

No entanto existem mais dois pontos importantes envolvidos nesta questão. 

1 - Geração de complexidade, como o @ffernandomoraes mencionou. E aqui eu nem arrisco falar sobre, pois não entendo de código.

2 - Acredito que seja uma funcionalidade que vai sumir. Depois de uma brevíssima pesquisa aqui (imagem anexo), vi que muito players do mercado não utilizam mais isso. No entanto acredito que só uma pesquisa mais aprofundada para explicar o porque do fenômeno e se devemos adotar ou não a mesma prática.

Nesse sentido. Eu não me preocuparia com isso neste momento. Pode ser que isso não exista mais daqui um tempo.


<img width="840" alt="image" src="https://user-images.githubusercontent.com/100154664/164773486-060214ab-10eb-46b6-85d3-fa208a2c4714.png">

**Comment by chriscorrales** [comment]
Legal galera, obrigado a todos que ajudaram e colocaram seus pontos aqui.
Vou fechar a issue, acho que já podemos tomar decisão que não viável, refleti melhor sobre entre ter e não ter, da na mesma coisa. O fato de não existir futuramente acho que torna isso aqui mais conclusivo possível kk.
