### ISSUE TITLE
Componente: List

### ISSUE THREAD

**Issue by danieloprado** [eduzz/houston#30]
**O que é:**
As Listas são elementos contínuos de forma horizontal que podem ou não conter imagens 

**Como usar:**
Usada para falar de um mesmo assunto, podendo conter ações complementares por textos, ícones e imagens. 

[Figma](https://www.figma.com/file/Z1MocTqXbRPGdaHMM9t4Zv/Houston-Design-System?node-id=3672%3A10747)

**Preview:**
![Preview](https://user-images.githubusercontent.com/7683575/110826547-f2b91d80-8273-11eb-80a7-2f2648d9c042.png)

**Comment by miguelaugl** [comment]
### Minha proposta RFC para esse componente é:
```
<List ...>
    <List.Item .../>
</List>;

Props:
  - List:
    - stripedRows: boolean;
  - List.Item:
    - title: React.ReactNode;
    - subtitle: React.ReactNode;
    - endIcon: React.ReactNode;
    - startIcon: React.ReactNode;
    - avatar: React.ReactNode;
```

**Comment by ChrisCorrales** [comment]
Não sei se avatar seria o ideal para imagem, talvez image mesmo seria legal.
Até por que avatar está ligado diretamente a uma imagem de alguém pessoa ou nick.
Nós poderemos usar tanto para imagem de produto quanto para outras coisas generalizadas.

**Comment by ffernandomoraes** [comment]
Então, é que no design remete literalmente à um avatar:

![image](https://user-images.githubusercontent.com/22228470/111688032-c8cea080-8809-11eb-9076-670a999b3ad5.png)

Fiquei meio em dúvida, realmente se alguém for inserir imagem (não tem essa aplicação no design) ele vai ter que colocar na prop `startIcon`. 

Sugestões?!

**Comment by danieloprado** [comment]
Ainda tem esse caso de texto no final:
![Captura de Tela 2021-03-18 às 16 56 07](https://user-images.githubusercontent.com/7683575/111689516-e6e8d080-880a-11eb-9036-0f6b3cc614f5.png)

Acho que poderia colocar um **endText** talvez.

Outra coisa **startIcon** e o **endIcon** acho que pode ter um **onClick**, pois podem ser ações.

Talvez podem ser um pouco diferente a estrutura:

```jsx
<List>
    <List.Item>
       <List.Left onClick={...}>
           <Icon />
       </List.Left >
       <List.Title>Teste</List.Title>
       <List.Subtitle>Teste</List.Subtitle >
       <List.Right onClick={...}>
           <Icon />
       </List.Right>
    </List.Item>
</List>
```
ou

```jsx
{ /* goste mais desse kk */}
<List>
    <List.Item>
       <List.Left icon={<Icon />} onClick={...} />
       <List.Title>Teste</List.Title>
       <List.Subtitle>Teste</List.Subtitle >
       <List.Right text='Texto' onClick={...} />
    </List.Item>
</List>
```

ou

```jsx
<List>
    <List.Item>
       <List.Left icon={<Icon />} onClick={...} />
       { /* não curto muito esse pois delimita só para titulo e subtítulo, não deixar algo diferente */}
       <List.Center title='Teste' subtitle='Sub' />
       <List.Right text='Texto' onClick={...} />
    </List.Item>
</List>
```

**Comment by miguelaugl** [comment]
Eu achei assim bem válido também:
```jsx
<List>
    <List.Item>
       <List.Left icon={<Icon />} onClick={...} />
       <List.Title>Teste</List.Title>
       <List.Subtitle>Teste</List.Subtitle >
       <List.Right text='Texto' onClick={...} />
    </List.Item>
</List>
```

**Comment by ffernandomoraes** [comment]
Curti também, é bastante componentes para algo simples mas acho que pela necessidade do design é válido. 

Obs: O `List.Right` pode conter também a prop `icon`.

**Comment by danieloprado** [comment]
@ffernandomoraes sim ele pode receber ou icon ou text

**Comment by ffernandomoraes** [comment]
@danieloprado e se ele preencher os dois, quem será exibido? Hehe Tanto no Left quanto no Right

**Comment by danieloprado** [comment]
@ffernandomoraes acredito que o icon possa sobrepor o text, o left não terá o text pois não tem design para isso.

**Comment by ffernandomoraes** [comment]
@danieloprado putz, verdade hahaha. Legal, gostei dessa ordem de exibição.

@miguelaugl não esquece de documentar isso.

**Comment by miguelaugl** [comment]
Atualizando a proposta:
```jsx
import List from '@eduzz/houston-ui/List';

<List>
    <List.Item>
       <List.Left icon={<Icon />} onClick={...} />
       <List.Title>Title</List.Title>
       <List.Subtitle>Subtitle</List.Subtitle >
       <List.Right text='Text' onClick={...} />
    </List.Item>
</List>
```

### List props

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| stripedRows | `boolean` | false    | -       | -           |

### List.Left props

| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| icon | `React.ReactNode` | false    | -       | Tem prioridade em relação ao image |
| onClick | `function` | false    | -       | -                                                                     |
| image | `React.ReactNode` | false    | -       | -                                                                     |


### List.Right props

| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| icon | `React.ReactNode` | false    | -       | Tem prioridade em relação ao title |
| onClick | `function` | false    | -       | -                                                                     |
| title | `string` | false | -        | -                                                                     |

### List.Title props
| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| children | `React.ReactNode` | true | -       | -                                                                     | 

### List.Subtitle props
| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| children | `React.ReactNode` | true | -       | -                                                                     |

**Comment by ffernandomoraes** [comment]
Perfeito. Por mim pode começar a codar 👌🏻

**Comment by ChrisCorrales** [comment]
Ficou show mesmo, parabéns !

**Comment by JonathasRodrigues** [comment]
muito bom, curti!

Será que não é uma boa adicionar um onClick no List.Item ?

**Comment by danieloprado** [comment]
@JonathasRodrigues até pensei nisso também, mas como tem um botão de ação do lado acho que não terá click no item

**Comment by ffernandomoraes** [comment]
Acredito que as props `OnClick`, `id`, `className`, `tabIndex`, etc... Sempre tem que estar disponível para uso em todos os componentes. Menos os componentes que não fazem nenhum sentido (que são poucos).
