### ISSUE TITLE
Componente: Breadcrumb

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#306]
**O que é:** 
O breadcrumb ajuda o usuário a visualizar a sua localização atual dentro da aplicação ou a sua localização em um contexto da aplicação, como etapas na criação de um produto. Também pode permitir o usuário clicar em uma etapa anterior para voltar para aquela localização.

Figma : 
https://www.figma.com/file/ipsAW0ruSaSTkQYqZnJUw9/Houston---desktop-core-components?node-id=363%3A6531

RFC : 

```jsx
import Breadcrumb from '@eduzz/houston-ui/Breadcrumb';

<Breadcrumb separator='>'>
  <Breadcrumb.Item>Meus Produtos</Breadcrumb.Item>
  <Breadcrumb.Item>
    <span>Lista</span>
    <div>Produtos </div> 
  </Breadcrumb.Item>
   <Breadcrumb.Item onClick={...} startIcon={<startIcon/>}>Novo Produto</Breadcrumb.Item>
   <Breadcrumb.Item endIcon={<endIcon/>}>Detalhes do Produto</Breadcrumb.Item>
</Breadcrumb>
```

### Breadcrumb props

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| separator | `string I React.ReactNode`  | false    | -       | -           |

### Breadcrumb.item props

| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| children | `string I React.ReactNode` | true    | -       |  |
| startIcon | `React.ReactNode` | false    | -       | -                                                                     |
| endIcon | `React.ReactNode` | false    | -       | -                                                                     |
| onClick | `function` | false    | -       | -                                                                     |

**Comment by miguelaugl** [comment]
E aí, mano, curti a proposta.

Se liga em algumas perguntas que tenho:
- O `<Breadcrumb.Item>` vai ser um link por padrão? Se sim, ele podia receber um `to` ou uma prop que tem a ver com a navegação em si, e se não o que acha dele receber uma prop chamada `as` para renderizar ele como um `<Link>` do react-router por exemplo?
- Acho também que seria legal o Breadcrumb.Item receber alguma prop para informar que ele é o ativo no momento, talvez `isCurrentPage` ou `isActive`.
- Outro ponto que a gente pode ver junto com o time de UX, é estabelecer um limite para o Breadcrumb, talvez se tiver sei lá, umas 10 páginas dentro, exibir só as três últimas e a primeira e o restante ser três pontinhos com um dropdown pra gente navegar (acredito que o mobile será assim).

**Comment by ffernandomoraes** [comment]
E aí Plinio. Alguns pontos.

**Breadcrumb**
- A prop `separator` não possui um valor default, seria legal ter algo. E não sei se uma string '>' é o ideal, talvez um ícone deste formato ficaria mais agradável visualmente.
- Não vamos ter o estado ativo de algum item? (Seria legal validar com algum designer).

**Breadcrumb Item**
- Existe um número limite?
- Visualizando o Figma, parece que não há possibilidade de existir um ícone depois do texto, então eu removeria a prop `endIcon` e renomearia a prop `startIcon` para apenas `icon`. Consequentemente a prop `children` não seria obrigatório, tendo em vista que pode ser apenas um ícone sem texto.
- Pensando na implementação no código, hoje seria basicamente assim:

```
<Breadcrumb>
  <Link to='...'>
    <Breadcrumb.Item>...</Breadcrumb.Item>
  </Link>

  <Link to='...'>
    <Breadcrumb.Item>...</Breadcrumb.Item>
  </Link>

  <Link to='...'>
    <Breadcrumb.Item>...</Breadcrumb.Item>
  </Link>

  <Link to='...'>
    <Breadcrumb.Item>...</Breadcrumb.Item>
  </Link>
</Breadcrumb>
```

Para ficar menos verboso e [seguir um padrão ja existente dentro de outro componente](https://github.com/eduzz/houston/blob/master/src/pages/ui-components/Layout/Sidebar/MenuItem/index.tsx), eu sugiro algo assim:

```
<Breadcrumb>
  <Breadcrumb.Item as={...} to='...'>...</Breadcrumb.Item>
  <Breadcrumb.Item as={...} to='...'>...</Breadcrumb.Item>
  <Breadcrumb.Item as={...} to='...'>...</Breadcrumb.Item>
  <Breadcrumb.Item as={...} to='...'>...</Breadcrumb.Item>
</Breadcrumb>
```

Onde o usuário consegue passar um wrapper para esse componente. Por exemplo: Link e NavLink do react-router-dom.

**Comment by phelpa** [comment]
Feedback providencial o de vocês, nova versão : 

RFC : 
```jsx
import Breadcrumb from '@eduzz/houston-ui/Breadcrumb';
import { Link } from 'react-router';

<Breadcrumb> //separator é opcional, o default vai ser um Icon '>' do design
  <Breadcrumb.Item>Meus Produtos</Breadcrumb.Item>
  <Breadcrumb.Item icon={<Icon/> isActive={true}/> {/*sem children e ativo*/}
  <Breadcrumb.Item>
    <span>Lista</span>
    <div>Produtos </div> {/*ainda permite children*/ }
  </Breadcrumb.Item>
  <Breadcrumb.Item as={<Link/>} to='/produtos' }>Novo Produto</Breadcrumb.Item>
</Breadcrumb>
```

Ficamos devendo de falar com o time de UX : 

1-) Estado ativo de um Breadcrumb.Item
2-) Estabelecer um limite de BreadCrumb.item. Possivelmente um '...' com dropdown, para atender a necessidade também do mobile.


### Breadcrumb props

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| separator | `React.ReactNode`  | false    | `<Icon/>`      | -           |

### Breadcrumb.item props

| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| children | `string I React.ReactNode` | false    | -       |  |
| icon | `React.ReactNode` | false    | -       | -                                                                     |
| to | `string` | false    | -       | -                                                                     |
| as | `React.ReactNode`  | false    | -       | -                                                                     |
| isActive | `boolean` | false    | -       | -                                                                     |

**Comment by ffernandomoraes** [comment]
Fechou pra mim!! 

Só um detalhe, no figma está dizendo que no mobile será ocultado.

**Comment by danieloprado** [comment]
Acho que poderia manter o onClick tambem, caso a pessoa precise.
