### ISSUE TITLE
Componente: Progress - Line (Steps)

### ISSUE THREAD

**Issue by danieloprado** [eduzz/houston#31]
**O que é:**
Usado durante um fluxo que possua várias etapas e que o usuário precise ter visibilidade do processo, pode ser chamado de **Steps** também.

[Figma](https://www.figma.com/file/Z1MocTqXbRPGdaHMM9t4Zv/Houston-Design-System?node-id=2628%3A8703)

**Preview:**
![Preview](https://user-images.githubusercontent.com/7683575/110827099-7ffc7200-8274-11eb-86c3-62cce8339e83.png)

**Comment by miguelaugl** [comment]
RFC:

```jsx
<ProgressLine stepsLabels={...} currentStepIndex={...} />
```
### ProgressLine props available

| prop             | type       | required | default | description |
|------------------|------------|----------|---------|-------------|
| stepsLabels | `string[]` | true     | -       | -           |
| currentStepIndex | `number`   | false    | 0       | -           |

**Comment by danieloprado** [comment]
Acho que talvez os steps podem ter mais de um estado, tipo skipped com um ícone diferente e error.
