### ISSUE TITLE
Componente: Tooltip

### ISSUE THREAD

**Issue by miguelaugl** [eduzz/houston#315]
**O que é:** 
O tooltip ajuda o usuário a identificar elementos e/ou descrever funcionalidades através de um texto informativo que é exibido ao passo que o usuário interage passa o mouse, clica ou foca em um elemento.

Figma : 
https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Houston-desktop-components-handoff?node-id=638%3A16574

RFC : 
Galera, analisando o quão complicado em questão de posicionamento e outros fatores é criar um tooltip ou qualquer elemento flutuante, acredito que devíamos utilizar essa lib: [Popper](https://popper.js.org/docs/v2/). O MUIV5 e o Chakra UI são alguns design system que já fazem uso dela, parece ser a melhor do mercado pra esse intuito mesmo.

```jsx
import Tooltip from '@eduzz/houston-ui/Tooltip';

<Tooltip placement='top-end'>
  <Button>...</Button>
</Tooltip>
```

### Tooltip props

| prop       | type                                             | required | default | description                                                                                                                                  |
| ---------- | ------------------------------------------------ | -------- | ------- | -------------------------------------------------------------------------------------------------------------------------------------------- |
| children   | `React.ReactNode`                                | `true`   | -       | Componente âncora. Se passado uma string, essa string será envolvida por uma tag `<span>` com `tabIndex=0` para que o usuário possa dar tab. |
| placement  | `top, right, left, bottom (variações start-end)` | `true`   | -       | Posição do tooltip em relação ao elemento âncora.                                                                                            |
| title      | `string`                                         | `true`   | -       | -                                                                                                                                            |
| open     | `boolean`                                        | `false`  | `false` | -                                                                                                                                            |
| disabled | `boolean`                                        | `false`  | `false` | -                                                                                                                                            |
| id         | `string`                                         | `false`  | -       | Se não informado, é utilizado um id auto-gerado.                                                                                             |
| onOpen     | `function`                                       | `false`  | -       | -                                                                                                                                            |
| onClose    | `function`                                       | `false`  | -       | -                                                                                                                                            |
| openDelay  | `number`                                         | `false`  | -       | -                                                                                                                                            |
| closeDelay | `number`                                         | `false`  | -       | -

**Comment by danieloprado** [comment]
Gostei do popper, por mim pode usar ele. Até vou dar uma olhada pois vou começar a mexer no select

**Comment by ffernandomoraes** [comment]
Alguma atualização desta issue?

**Comment by phelpa** [comment]
Precisa dessa prop 'disabled'? serviria para quê?  Mesma coisa com a prop 'id', tem algum motivo?

O 'openDelay' e 'closeDelay' vamos deixar aberto mesmo? Teria alguma necessidade do dev ter controle desses tempos? Não dá pra deixar um padrão e acabou?

O placement default do tooltip atual é 'top', deixamos assim? Ou vamos obrigar o dev a setar um placement?

Tem alguma necessidade do dev controlar quando o tooltip vai estar 'Open'? O comportamento não é deixar sempre o tooltip mostrando se o usuário está dando hover/focus ?

**Comment by ffernandomoraes** [comment]
> Precisa dessa prop 'disabled'? serviria para quê? Mesma coisa com a prop 'id', tem algum motivo?
> O 'openDelay' e 'closeDelay' vamos deixar aberto mesmo? Teria alguma necessidade do dev ter controle desses tempos? Não dá pra deixar um padrão e acabou?
> 
> O placement default do tooltip atual é 'top', deixamos assim? Ou vamos obrigar o dev a setar um placement?
> 
> Tem alguma necessidade do dev controlar quando o tooltip vai estar 'Open'? O comportamento não é deixar sempre o tooltip mostrando se o usuário está dando hover/focus ?

E aí querido. Ao meu ver seria legal manter a prop `disabled`, um exemplo simples que já aconteceu comigo: em algum cenário X algo está desabilitado e naquele momento ao passar o mouse em cima de um componente Y não é pra ser exibido o Tooltip explicando. Faz sentido?

Os `id` da vida sempre é bom manter, não faz mau pra ngm e contribui com os testes.

As props `openDelay` e `closeDelay` não vejo necessidade, já que é algo que despadroniza os Tooltips.

Sobre o `placement` podemos manter como `top` o padrão. Obrigar alguém a colocar uma prop que pode possuir um valor default é meio ruim.

Hm, sobre o `open`, não consigo pensar um caso onde o Tooltip sempre vai estar ativo, por mim pode remover.
