### ISSUE TITLE
Componente: Dropdown

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#319]
**O que é:** 
Quando houver mais do que algumas opções para escolher, você pode envolvê-las em um menu suspenso. Ao passar o mouse ou clicar em um item um menu suspenso aparecerá, permitindo que você escolha uma opção e execute a ação relevante.

Figma : 
https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Houston-desktop-components-handoff?node-id=775%3A20263

RFC : 

```jsx
import Dropdown from '@eduzz/houston-ui/Dropdown';

<Dropdown placement='bottomRight' trigger='click' isOpen> //todos esses são opcionais
  <Dropdown.Anchor>
     <Button>Options</Button>
  <Dropdown.Anchor>
  <Dropdown.Content>
     <List>
       <List.Item>
         <List.Text title="Item1" />
       </List.Item>
       <List.Item>
         <List.Text title="Item2" />
       </List.Item>
     </List>
  <Dropdown.Content>
</Dropdown>
```

### Dropdown props

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| placement | `bottomLeft, bottom, bottomRight, topLeft, top, topRight`  | false    | `bottomLeft`      | -           |
| trigger | `click I hover`  | false    | `hover`       | -           |
| isOpen | `boolean`  | false    | `false`       | -           |

### Dropdown.Anchor props

| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| children | `React.ReactNode` | true    | -       |  |

### Dropdown.Content props

| prop      | type              | required | default | description                                                           |
|-----------|-------------------|----------|---------|-----------------------------------------------------------------------|
| children | ` React.ReactNode` | true    | -       |  |

**Comment by miguelaugl** [comment]
Legal, mano, curti.

Sobre a composição do componente achei muito bacana, a abordagem do MUI que precisa passar ref pro anchor toda vez é meio zoada porque você precisa ficar importando ref e passando pro componente toda hora, além de ficar setando e resetando o anchor. @danieloprado talvez tenha como usar essa mesma lógica lá no popover.

Alguns pontos, veja se faz sentido:

- Cara, normalmente o `dropdown` sempre fica em baixo do componente, por isso o nome, então não sei se o placement faz sentido nesse caso;
- Mais uma vez falando sobre a composição, acho que a gente poderia ter um `Dropdown.Trigger` para podermos isolar o trigger para algo fora da âncora ou até mesmo um item menor da âncora, o que acha?
- Sobre a prop `trigger`, acho que o default podia ser `click`;
- Gosto de `onOpen` ou em `onClose`, acho sempre bacana dar espaço pro usuário fazer algum controle se necessário. Por exemplo: metrificar quantas pessoas abriram o dropdown ou coisa assim.

**Comment by phelpa** [comment]
> Legal, mano, curti.
> 
> Sobre a composição do componente achei muito bacana, a abordagem do MUI que precisa passar ref pro anchor toda vez é meio zoada porque você precisa ficar importando ref e passando pro componente toda hora, além de ficar setando e resetando o anchor. @danieloprado talvez tenha como usar essa mesma lógica lá no popover.
> 
> Alguns pontos, veja se faz sentido:
> 
> * Cara, normalmente o `dropdown` sempre fica em baixo do componente, por isso o nome, então não sei se o placement faz sentido nesse caso;
> * Mais uma vez falando sobre a composição, acho que a gente poderia ter um `Dropdown.Trigger` para podermos isolar o trigger para algo fora da âncora ou até mesmo um item menor da âncora, o que acha?
> * Sobre a prop `trigger`, acho que o default podia ser `click`;
> * Gosto de `onOpen` ou em `onClose`, acho sempre bacana dar espaço pro usuário fazer algum controle se necessário. Por exemplo: metrificar quantas pessoas abriram o dropdown ou coisa assim.

1-) Sua sugestão seria colocar somente bottomLeft, bottom e bottomRight? Nesse caso não é melhor aproveitar o embalo e fazer os top também?

2-) Tem algum use case que demonstre essa necessidade? Realmente só para eu entender

3-) Por mim Ok

4-) Faz sentido

**Comment by ffernandomoraes** [comment]
Olha quem voltou hehe
