### ISSUE TITLE
Componente: Progress - Circle

### ISSUE THREAD

**Issue by danieloprado** [eduzz/houston#32]
**O que é:**
Usado durante um fluxo que possua várias etapas e que o usuário precise ter visibilidade do processo.

[Figma](https://www.figma.com/file/Z1MocTqXbRPGdaHMM9t4Zv/Houston-Design-System?node-id=2628%3A8703)

**Preview**
![Preview](https://user-images.githubusercontent.com/7683575/110827537-eed9cb00-8274-11eb-9f6b-c7a0eaf0250a.png)

**Comment by micheleambrosio** [comment]
_Olá! Primeiro componente que vou estar criando, então, fiquem à vontade para sugerir melhorias (hahaha)_

Seguindo o RFC do ProgressLine, que é um componente semelhante, pensei em algo assim para o CircularProgress:

```tsx
import CircularProgress, { useCircularProgress } from '@eduzz/houston-ui/Button';

const { nextStep, backStep, activeStep } = useCircularProgress();

<ProgressLine maxSteps={4}  currentStep={activeStep} type={percentage} />
```

**Propriedades**

|prop       | tipo          | obrigatório         | padrão         | descrição            |
|-----------|--------------|-----------------------|------------------|------------------------|
|maxSteps|number|`true`                     | -                   | Define o máximo de passos do progresso |
|currentStep|number|`false`                     | 1                   | Define o passo atual do progresso |
|type | `numeric`, `percentage`|`false`                     | `numeric`                   | Define o tipo do progresso circular, se será exibido em porcentagem ou números |
|error|`boolean`|`false`                     |`false`                  | Altera a cor do progresso circular para vermelho para mostrar que possui erro no processo |

**Comment by ffernandomoraes** [comment]
Por mim, fechou!
