### ISSUE TITLE
Definições do componente Alert.

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#331]
Pessoal comecei a desenvolver e me questionei qual seria melhor implementação no código deste componente.

Hoje: 
```jsx
<Alert type="error">
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
</Alert>
  ```

Antes de exibir as novas opções, gostaria que levassem em consideração as regras de design:
- Sempre haverá um icone do tipo (positive, negative, informative e warning)
- Título é opcional
- Botão de fechar (x) é opcional
- Botão de ação (CTA) é opcional e só pode haver no máximo um. Todas as props do botão deverão estar disponível para uso.
- Não há variação de texto (peso, tamanho de font, etc..) dentro do conteúdo.

Depois da refatoração, eu pensei em duas implementações:

1. Componentes isolados, lidando com suas responsabilidades. Porém código mais verboso e sem controle de algumas regras de design (apenas um botão, apenas um título, etc), mas acredito que isso não seja um problema.
```jsx
<Alert type='informative' {...props}>
  <Alert.Title>Atenção!</Alert.Title>
  <Alert.Content>
    Alert pode ser utilizado para mostrar mensagens de atualizações para os usuários, sejam atualizações de
    segurança ou de interface. O objetivo é avisar e não guiar o caminho para o usuário.
  </Alert.Content>
  <Alert.Button {...buttonProps}>Fechar</Alert.Button>
</Alert>
```

2. Código mais limpo, controle das regras de design, mas talvez o uso a mais de algumas props não me agradou muito.
```jsx
<Alert type='informative' title='Atenção!' buttonText='Fechar' buttonProps={...}>
  Alert pode ser utilizado para mostrar mensagens de atualizações para os usuários, sejam atualizações de
  segurança ou de interface. O objetivo é avisar e não guiar o caminho para o usuário.
</Alert>
```

Em ambos os casos agente sai perdendo de algum lado, mas não é nada exagerado.

Enfim, o que acham? Fiquem a vontade de propor uma nova implementação.

**Comment by miguelaugl** [comment]
Gosto mais da segunda implementação, acho que poderia ter um actionProps que recebesse todas as props do botão e o children a gente podia chamar de text pra não confundir o usuário.

**Comment by phelpa** [comment]
E assim ?

```jsx
<Alert type='informative' title='Atenção!'>
  Alert pode ser utilizado para mostrar mensagens de atualizações para os usuários, sejam atualizações de
  segurança ou de interface. O objetivo é avisar e não guiar o caminho para o usuário.
  <Alert.Button {...buttonProps}>Fechar</Alert.Button>
</Alert>
```

Pareceu certo deixar somente o Alert.Button como um outro componente já que esse é o único que vai ser customizável

**Comment by danieloprado** [comment]
Prefiro a idéia inicial com o Title separado por que da para customizar melhor. Gosta da ideia dos componentes separados.

**Comment by ffernandomoraes** [comment]
> E assim ?
> 
> ```js
> <Alert type='informative' title='Atenção!'>
>   Alert pode ser utilizado para mostrar mensagens de atualizações para os usuários, sejam atualizações de
>   segurança ou de interface. O objetivo é avisar e não guiar o caminho para o usuário.
>   <Alert.Button {...buttonProps}>Fechar</Alert.Button>
> </Alert>
> ```
> 
> Pareceu certo deixar somente o Alert.Button como um outro componente já que esse é o único que vai ser customizável

Neste caso, teria que ser assim:
```jsx
<Alert type='informative' title='Atenção!'>
  <Typography.Paragraph color='neutralColor.low.pure' size='sm' lineHeight='lg'>
    Alert pode ser utilizado para mostrar mensagens de atualizações para os usuários, sejam atualizações de
    segurança ou de interface. O objetivo é avisar e não guiar o caminho para o usuário.
  </Typography.Paragraph>

  <Alert.Button {...buttonProps}>Fechar</Alert.Button>
</Alert>
```

O conteúdo tem um estilo especifico. Acho ruim deixar em aberto assim.

**Comment by ffernandomoraes** [comment]
> Prefiro a idéia inicial com o Title separado por que da para customizar melhor. Gosta da ideia dos componentes separados.

Então, mas eu fiquei pensando em: "Em que momento eu customizaria um alert?" "Quando eu colocaria uma condição dentro de um alert?", etc...

Gosto também da ideia de ser separado, mas neste caso não estou achando tão vantajoso essa divisão.
