### ISSUE TITLE
Componente : Divider

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#336]
**O que é:** 
Dividers são usados para fazer uma separação visual de um conteúdo.

Figma : 
https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Houston-desktop-components-handoff?node-id=1607%3A32210

RFC : 

```jsx
import Divider from '@eduzz/houston-ui/Divider';

<Divider vertical color='neutral.low.dark' margin/> //tudo optional
```
Conversando com o Milton achamos uma boa deixar o color aberto, aí pensei em usar como usamos no Typography.

Também vi que no typography usamos um marginBottom ai achei uma boa usar aqui também. Não sei porque foi usado marginBottom ao invés de margin (nesse caso a margin seria bottom e top) no Typography então abro a discussão : Usar margin? Se sim, marginBottom ou margin?

### Divider props

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| vertical | `boolean `  | false    | false     | -           |
| color | `string `  | false    | neutralColor.low.pure     | -           |
| margin | `boolean `   | false    | false     | -           |

**Comment by ffernandomoraes** [comment]
E aí plinioty, boa!

Vamos lá, por padrão acho que o componente deveria ser horizontal (por ser mais comum o uso).

Sinceramente não sei se devemos colocar margin nos componentes, por N motivos. Com isso a longo do projeto foi criado um componente pra controlar esses casos (https://eduzz.github.io/houston/ui-components/Box). O componente controla margin e padding em diferentes resoluções, o que abrange 100% dos casos, será que não seria melhor deixar essa responsabilidade para esse componente (Box)?

**Comment by ffernandomoraes** [comment]
Maravilha, então podemos remover essa prop `margin`. De resto, acredito que seja isso mesmo, manda bala!
