### ISSUE TITLE
Adicionar selection na List e na Table

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#361]
O @JonathasRodrigues  https://github.com/eduzz/houston/issues/123 já sugeriu adicionar um selection na table de forma 'nativa' e eu acho uma boa idéia, agora quero estender a discussão para o List também.

No design temos selection na list : 
![image](https://user-images.githubusercontent.com/17049866/177556702-f3522fe5-1558-40e1-8725-775c3caf7c47.png)

e na table : 
![image](https://user-images.githubusercontent.com/17049866/177557509-887b1290-6591-4fe3-b029-3fde21504d55.png)

O antd implementa na table deles uma api para selecionar as linhas, acho que seria interessante fazermos isso para a nossa table e como a list tem também elementos selecionáveis acho que faria sentido fazer nela também.

O que vocês acham?

Pensei em algo assim : 

Na list : 
```
<List rowSelectionType='checkbox' onRowSelect={}>
  <List.Item>
    <List.Left icon={<InsertEmoticonIcon />} />
    <List.Text title="Lorem Ipsum Dolor" subtitle="Lorem Ipsum Dolor" />
    />
  </List.Item>
  <List.Item>
    <List.Left icon={<InsertEmoticonIcon />} />
    <List.Text title="Lorem Ipsum Dolor" />
    />
  </List.Item>
```
Na Table : 

```
<Table rowSelectionType='checkbox' onRowSelect={}>
  <Table.Header>
    <Table.Column width={50} sortableField="id">
      #
    </Table.Column>
    <Table.Column sortableField="name">Nome</Table.Column>
    <Table.Column sortableField="email">Email</Table.Column>
    <Table.Column align="right">Valor</Table.Column>
  </Table.Header>
  <Table.Body>
      ......
  ```
No onRowSelect passaria no callback uma array com o data e o index das linhas (que nem hoje é feito quando clica no Table.option)

Se fôssemos deixar na mão do dev ficaria assim : 

```
<List>
  <List.Item>
    <List.Left><Checkbox/></List.Left>
    <List.Text title="Lorem Ipsum Dolor" subtitle="Lorem Ipsum Dolor" />
  </List.Item>
  <List.Item isActive>
    <List.Left><Checkbox/></List.Left>
    <List.Text title="Lorem Ipsum Dolor" />
  </List.Item>
</List>
  ```

A gente permitiria ele setar uma prop _isActive_ e ele que teria que fazer o controle da checkbox (seria algo dessa forma na Table também).

O que vocês acham? Seria uma feature bacana? Ou melhor deixar na mão do dev mesmo?

**Comment by phelpa** [comment]
```
const form = useForm()

<Form context={form} >
  <List>
    <List.Item>
      <List.Left><Checkbox name='checkbox1'/></List.Left>
      <List.Text title="Lorem Ipsum Dolor" subtitle="Lorem Ipsum Dolor" />
    </List.Item>
    <List.Item isActive>
      <List.Left><Checkbox name='checkbox2'/></List.Left>
      <List.Text title="Lorem Ipsum Dolor" />
    </List.Item>
  </List>
</Form>
```

Se der console.log no form.values acho que ficaria  

```
{
  checkbox1 : false,
  checkbox2 : true
}
```

E seria um jeito simples de fazer usando o nosso useForm, tiraria a necessidade de fazer isso de forma nativa. Vou testar isso aqui depois.

**Comment by miguelaugl** [comment]
Mano, gosto da ideia de ter nativamente lá essa opção dentro da nossa lib, boa!

**Comment by phelpa** [comment]
> Mano, gosto da ideia de ter nativamente lá essa opção dentro da nossa lib, boa!

Eu que achei a ideia boa agora não to achando mais hahahah

Olha como deu pra fazer um componente de lista com checkbox de forma simples usando o useForm : 

```
const ComponentsDev = () => {
  const form = useForm({ onSubmit: values => console.log(values, 'values') });
  const { values } = form;
  return (
    <Form context={form}>
      <List stripedRows>
        <List.Item isActive={values.checkbox1}>
          <List.Left>
            <Checkbox name='checkbox1' />
          </List.Left>
          <List.Text title='Lorem Ipsum Dolor' subtitle='Lorem Ipsum Dolor' />
          <List.Right icon={<InsertEmoticonIcon />} />
        </List.Item>
        <Divider />
        <List.Item isActive={values.checkbox2}>
          <List.Left>
            <Checkbox name='checkbox2' />
          </List.Left>
          <List.Text title='Lorem Ipsum Dolor' subtitle='Lorem Ipsum Dolor' />
          <List.Right icon={<InsertEmoticonIcon />} />
        </List.Item>
        <Divider />
        <List.Item isActive={values.checkbox3}>
          <List.Left>
            <Checkbox name='checkbox3' />
          </List.Left>
          <List.Text title='Lorem Ipsum Dolor' subtitle='Lorem Ipsum Dolor' />
          <List.Right icon={<InsertEmoticonIcon />} />
        </List.Item>
        <Divider />
        <List.Item isActive={values.checkbox4}>
          <List.Left>
            <Checkbox name='checkbox4' />
          </List.Left>
          <List.Text title='Lorem Ipsum Dolor' subtitle='Lorem Ipsum Dolor' />
          <List.Right icon={<InsertEmoticonIcon />} />
        </List.Item>
        <Divider />
      </List>
    </Form>
  );
};
```

Resultado : 

![image](https://user-images.githubusercontent.com/17049866/177594446-385f4131-e740-4198-884b-266362bcb75d.png)

Valor do form.values nesse caso da imagem : 

```{checkbox3: true, checkbox4: true, checkbox2: true} ```

**Comment by miguelaugl** [comment]
Mas você não tá tirando nada com esses valores, você não sabe qual row está selecionada por exemplo, são checkboxes que precisam de names específicos não é a forma ideal de resolver, além de que acho que uma lista selecionável é mais usado sem um form do que com um form em si.
Ter nativamente algo que já controla assim como o ANTD faz é muito interessante, porque se a pessoa que fazer essa seleção sem usar necessariamente um form, ela não teria que adicionar o checkbox manualmente, etc.

**Comment by ffernandomoraes** [comment]
Hm, eu tenho alguns pensamentos sobre:

- É bom/legal facilitar em alguns casos? Sim
- É muito trabalhoso o usuário implementar isso? Não
- Só vai ter `Checkbox` como opção? Se amanhã for inserido o `Radio`, vamos ter que mapear internamente. MAS o Radio funciona diferente do Checkbox (um é valor único e o outro pode ser múltiplos valores), a lógica entre eles muda, então ja começaria a ganhar complexibilidade o componente ou precisaríamos adicionar mais códigos para validar os tipos.

Minha única preocupação em relação a essas "ajuda" é se responsabilizar por algo que talvez não deveríamos, e ficar criando complexibilidade pro código do Houston.

Existem outras abordagens genéricas mais fáceis, onde o usuário fica responsavel por dizer quem está ativo, por exemplo:

```
<List itemsActive=['item-1']>
  <List.Item name='item-1'>
    <List.Left>
      <Checkbox name='checkbox1' />
    </List.Left>
    <List.Text title="Lorem Ipsum Dolor" subtitle="Lorem Ipsum Dolor" />
  </List.Item>

  <List.Item name='item-2'>
    <List.Left>
      <Checkbox name='checkbox2'/>
    </List.Left>
    <List.Text title="Lorem Ipsum Dolor" />
  </List.Item>
</List>
```

Ou até mesmo uma prop individual `isActive`.

Resumindo, eu acho que deveríamos dar apenas o estado (css), como vai ser implementado isso fica a critério do DEV.
