### ISSUE TITLE
Componente : TagHighlight

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#373]
**O que é:** 
Badges são usadas para destacar o status de um item.

No design está sendo chamado de TagHighlight, pensei em até unificarmos com o TagSelect mas a altura e uns paddings do TagHighlight são diferentes e não tem comportamentos como click, o hover é diferente e outras coisas.

Então ficaria **_TagHighlight_** = **_Badge_** e **_TagSelect_** = **_Tag_**.  O que vocês acham?

Figma : 
https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=2875%3A70966

![image](https://user-images.githubusercontent.com/17049866/179544034-76649515-60be-4f0f-bbe0-5bf2305b46fe.png)

RFC : 

```jsx
import Badge from '@eduzz/houston-ui/Badge';

<Badge color='feedbackColor.positive.pure' type='outlined'>Default</Badge> //color seria todas as cores dos tokens
```

### Badge props

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| color | `string `  | false    | -   | -           |
| type | `outline I filled `   | false    | filled     | -           |

**Comment by ffernandomoraes** [comment]
Cara, acho que esse componente não pode se chamar Badge. 

Badge seria mais um componente com esse comportamento:
<img width="287" alt="image" src="https://user-images.githubusercontent.com/22228470/179782469-e7681d7f-6353-47d7-ac27-ed17e8d2fd53.png">
<img width="170" alt="image" src="https://user-images.githubusercontent.com/22228470/179782550-0a86f318-5134-4ed3-9c36-49ad90aa1c22.png">

Eu procuraria alguma solução pra unificar as tags em um só lugar ou chamaria de TagHighlight mesmo, por que elas não mudam tanto. Um modificador não resolveria esse problema?

`--tag-highlight` -> esconde os elementos que não podem aparecer
`--tag-color-xpto` -> pinta o fundo

**Comment by phelpa** [comment]
> Cara, acho que esse componente não pode se chamar Badge.
> 
> Badge seria mais um componente com esse comportamento: <img alt="image" width="287" src="https://user-images.githubusercontent.com/22228470/179782469-e7681d7f-6353-47d7-ac27-ed17e8d2fd53.png"> <img alt="image" width="170" src="https://user-images.githubusercontent.com/22228470/179782550-0a86f318-5134-4ed3-9c36-49ad90aa1c22.png">
> 
> Eu procuraria alguma solução pra unificar as tags em um só lugar ou chamaria de TagHighlight mesmo, por que elas não mudam tanto. Um modificador não resolveria esse problema?
> 
> `--tag-highlight` -> esconde os elementos que não podem aparecer `--tag-color-xpto` -> pinta o fundo

Eu vi que o chakra chama esse componente de Badge mesmo mas não tinha visto que o material-ui e ant-d chama essa notificação de Badge também.

Unificar eu acho bem complicado porque a Tag tem muitas funcionalidades que esse componente não precisa, este componente é mais para dar um highlight mesmo e o Tag é meio que um botão que você pode dar Toggle. Por enquanto acho que vou chamar de TagHighlight mesmo então.
