### ISSUE TITLE
Componente : Tag

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#374]
**O que é:** 

O componente Tag é usado para itens que precisam ser rotulados, categorizados ou organizados usando palavras-chave.

Figma : 
https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=2425%3A51851

![image](https://user-images.githubusercontent.com/17049866/179548547-0c09037c-fbcb-42e3-8045-35939cdd6a1e.png)
![image](https://user-images.githubusercontent.com/17049866/179550800-20af47b8-50d7-46d2-96a6-40b5e2d88491.png)

RFC : 

```jsx
import Tag from '@eduzz/houston-ui/Tag';

  <Tag isActive/>
    <Tag.Avatar onClick={() => console.log(cliquei no Avatar)}/>
    <Tag.PlusIcon onClick={() => console.log(cliquei no +)}/>
    <Tag.Label onClick={() => console.log(cliquei no Text)}>TagSelect</Tag.Label>
    <Tag.CloseIcon onClick={() => console.log(cliquei no X)}/>
  </Tag>
```
To pensando em deixar a Tag totalmente controlled, o cara que usar que decide o que vai acontecer através dos onClicks que ele passar.

A cor vai ser sempre brandColor, ele é tipo um botão

### Tag

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| children | `React.ReactNode` | true    | -       |  |
| isActive | `boolean` | false    | false      |  |
| disabled | `boolean` | false    | false      |  |
| onClick | `Function` | false    | false      |  |

### Tag.Avatar
Mesmas props que o Avatar só que com o xs chumbado
| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| onClick | `Function` | false    | -       |  |

### Tag.PlusIcon
| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| onClick | `Function` | false    | -       |  |

### Tag.Label

| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| children | `string` | true    | -       |  |
| onClick | `Function` | false    | -       |  |

### Tag.CloseIcon
| prop        | type      | required | default | description |
|-------------|-----------|----------|---------|-------------|
| onClick | `Function` | false    | -       |  |

**Comment by ffernandomoraes** [comment]
Fala meu monstro!

Cara, fiquei pensando nessa implementação, será que é valida? Não vai ser diferente das outras implementações que estamos fazendo? Acho que deveríamos seguir o mesmo conceito da List (`Tag.Left`, `Tag.Right`...). Algo genérico, reduzindo responsabilidades do componente. Por que se amanhã surgir um novo componente interno, "não vamos se preocupar tanto com isso".

Repare o exemplo do Chakra UI (ignore as props, foque na implementação), eles controlam apenas no CSS os elementos internos:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/22228470/179780838-f40ee795-8b7f-41ec-9fa6-62fe1ca54067.png">


Eu seguiria com algo assim:

```jsx
import Tag from '@eduzz/houston-ui/Tag';

<Tag closable onClose={}>
  <Tag.Left>...</Tag.Left>
  <Tag.Text>...</Tag.Text>
  <Tag.Right>...</Tag.Right>
</Tag>
``` 

Se o `onClose` for passado, adiciona o `X` no final. Ou talvez uma prop que controle isso `closable`.

**Comment by phelpa** [comment]
> Ah outro ponto, não se preocupe agora com essa prop `isActive`, por que isso entra meio na nossa discussão de como faremos nosso suporte ao dark mode. Por hora pode ignorar!!



> Fala meu monstro!
> 
> Cara, fiquei pensando nessa implementação, será que é valida? Não vai ser diferente das outras implementações que estamos fazendo? Acho que deveríamos seguir o mesmo conceito da List (`Tag.Left`, `Tag.Right`...). Algo genérico, reduzindo responsabilidades do componente. Por que se amanhã surgir um novo componente interno, "não vamos se preocupar tanto com isso".
> 
> Repare o exemplo do Chakra UI (ignore as props, foque na implementação), eles controlam apenas no CSS os elementos internos: <img alt="image" width="823" src="https://user-images.githubusercontent.com/22228470/179780838-f40ee795-8b7f-41ec-9fa6-62fe1ca54067.png">
> 
> Eu seguiria com algo assim:
> 
> ```js
> import Tag from '@eduzz/houston-ui/Tag';
> 
> <Tag closable onClose={}>
>   <Tag.Left>...</Tag.Left>
>   <Tag.Text>...</Tag.Text>
>   <Tag.Right>...</Tag.Right>
> </Tag>
> ```
> 
> Se o `onClose` for passado, adiciona o `X` no final. Ou talvez uma prop que controle isso `closable`.

Eu na real prefiro desse jeito do Left, Right, acho que acertamos isso na List e é um bom padrão. Eu não sugeri isso porque no design o componente não tá 'aberto', diferente do List, mas eu gosto desse jeito, acho que a gente consegue atingir o design e deixar o componente flexível.

E achei boa a idéia do onClose, tava perdido com o que fazer com o 'X' e achei uma boa solução, se passou onClose adiciona o X.

**Comment by phelpa** [comment]
> Ah outro ponto, não se preocupe agora com essa prop `isActive`, por que isso entra meio na nossa discussão de como faremos nosso suporte ao dark mode. Por hora pode ignorar!!

Esse isActive seria pro componente ficar 'ativo' mesmo, na hora que o cara clica na Tag ele poderia setar o isActive para true para ficar preenchido.
