### ISSUE TITLE
Componente: Showcase

### ISSUE THREAD

**Issue by MatheusRaj** [eduzz/houston#380]
**O que é:** 
Modal com steps informando o usuário sobre um assunto.

Figma : 
https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=2178%3A50337

![image](https://user-images.githubusercontent.com/38676242/180219487-a5f6199e-6336-4610-827b-1e5540897dce.png)

RFC : 

```jsx
import Showcase from '@eduzz/houston-ui/Showcase';

<Showcase controlDots={true|false}>
  <Showcase.Step>
    <Showcase.Image src='https://video.jpg' />
    <Showcase.Title>Envie vídeos!</Showcase.Title>
    <Showcase.Text>Envie vídeos aqui</Showcase.Text>
    <Showcase.Footer>
      <Button variant='text' onClick={onClose}>Cancelar</Button>
      <Button>Continuar</Button>
    </Showcase.Footer>
  </Showcase.Step>
  
  <Showcase.Step>
    <Showcase.Image src='https://imagem.jpg' />
    <Showcase.Title>Envie imagens!</Showcase.Title>
    <Showcase.Text>Envie imagens aqui</Showcase.Text>
    <Showcase.Footer>
      <Button variant='text' onClick={onClose}>Fim</Button>
    </Showcase.Footer>
  </Showcase.Step>
</Showcase>
```

### Showcase props

| prop                 | tipo                       | obrigatório | padrão  | descrição                                              |
| -------------------- | -------------------------- | ----------- | ------- | ------------------------------------------------------ |
| open                 | `boolean`                  | `false`     | `true`  | Controla o estado aberto/fechado do componente         |
| initialStep          | `number`                   | `false`     | 1       | Indica em qual passo o componente será renderizado     |
| onNext               | `Function`                 | `false`     | -       | -                                                      |
| onPrevious           | `Function`                 | `false`     | -       | -                                                      |
| onFinish             | `Function`                 | `false`     | -       | -                                                      |
| onClose              | `Function`                 | `false`     | -       | -                                                      |
| stepCounter          | `boolean`                  | `false`     | `true`  | Se `true`, exibe o contador de passos totais e o atual |
| disableBackdropClick | `boolean`                  | `false`     | `true`  | -                                                      |

### Showcase.Image

| prop | tipo     | obrigatório | padrão | descrição |
| ---- | -------- | ----------- | ------ | --------- |
| src  | `string` | `true`      | -      | -         |
| alt  | `string` | `true`      | -      | -         |

**Comment by ffernandomoraes** [comment]
E ai math, cade a implementação com os botões do footer? Atualiza pra nós ter 100% do contexto.

**Comment by ffernandomoraes** [comment]
Uma dúvida, essa imagem é fixa para todas as etapas ou cada etapa pode ter sua imagem? (Valide com um designer isso, por que isso pode mudar muita coisa).

**Comment by phelpa** [comment]
Acho que não precisa do 'size' porque pelo que vi no figma vai ter uma largura só.  

Cada ShowCase.Step seria uma etapa? Nesse meu exemplo abaixo seriam duas etapas?

A prop 'stepCounter' seria para mostrar ou não o controlDots? faz sentido.

Não me preocuparia com os breaking changes, a gente tá reformulando geral mesmo e estamos documentando nas releases as mudanças.

O footer pensei desse jeito aí do exemplo, vai bater com o Dialog : https://github.com/eduzz/houston/pull/379 e você não precisaria desse StepButtons, GenericButtons, PreviousButton e etc....Cada etapa teria os botões que você decidir colocar, e caminharia para linha que estamos indo de deixar os componentes mais abertos (desde que atenda o design).

```jsx
   import Showcase from '@eduzz/houston-ui/Showcase';

    <Showcase stepCounter>
      <Showcase.Step>
       <Showcase.Image src='https://cdn.pixabay.com/photo/2021/05/22/17/06/hybrid-6274156_960_720.jpg' />
        <Showcase.Title>Envie vídeos!</Showcase.Title>
        <Showcase.Text>
          Envie vídeos aqui
        </Showcase.Text>
      <Showcase.Footer>
        <Button variant='text' onClick={onClose}>Cancelar</Button>
        <Button>Continuar</Button>
      </Showcase.Footer>
      </Showcase.Step>
      <Showcase.Step>
         <Showcase.Image src='https://cdn.pixabay.com/photo/2021/05/22/17/06/hybrid-6274156_960_720.jpg' />
        <Showcase.Title>Envie imagens!</Showcase.Title>
        <Showcase.Text>
          Envie imagens aqui
        </Showcase.Text>
        <Showcase.Footer>
          <Button variant='text' onClick={onClose}>Fim</Button>
        </Showcase.Text>
        <Showcase.Footer>
          <Button>Continuar</Button>
      </Showcase.Footer>
      </Showcase.Step>
    </Showcase>
```

**Comment by ffernandomoraes** [comment]
Também sigo na ideia no @phelpa , por isso pedi o exemplo completo. Acho que muitas props não fazem mais sentido.

Eu sugiro uma implementação assim:

```jsx
import Showcase from '@eduzz/houston-ui/Showcase';

<Showcase controlDots={true|false}>
  <Showcase.Step>
    <Showcase.Image src='https://video.jpg' />
    <Showcase.Title>Envie vídeos!</Showcase.Title>
    <Showcase.Text>Envie vídeos aqui</Showcase.Text>
    <Showcase.Footer>
      <Button variant='text' onClick={onClose}>Cancelar</Button>
      <Button>Continuar</Button>
    </Showcase.Footer>
  </Showcase.Step>
  
  <Showcase.Step>
    <Showcase.Image src='https://imagem.jpg' />
    <Showcase.Title>Envie imagens!</Showcase.Title>
    <Showcase.Text>Envie imagens aqui</Showcase.Text>
    <Showcase.Footer>
      <Button variant='text' onClick={onClose}>Fim</Button>
    </Showcase.Footer>
  </Showcase.Step>
</Showcase>
```

**Comment by MatheusRaj** [comment]
Boa rapaziada, gostei das mudanças, deu uma simplificada boa.

**Comment by ffernandomoraes** [comment]
Boa, marcha!
