### ISSUE TITLE
Componente : Tabs

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#390]
**O que é:** 
As Tabs facilitam a exploração e alternam entre diferentes visualizações.
As Tabs organizam e permitem a navegação entre grupos de conteúdo relacionados e no mesmo nível hierárquico.

Figma : 
horizontal : https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=1009%3A20147
vertical : https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=3360%3A67124

![image](https://user-images.githubusercontent.com/17049866/180886396-ac7b1955-f31f-4008-b8ea-3611920101bb.png)
![image](https://user-images.githubusercontent.com/17049866/180886630-03ea9973-9fab-4fdb-9de2-ce935e0b58f0.png)

RFC : 

```jsx
import Tabs from '@eduzz/houston-ui/Tabs';
 const { Tab } = Tabs;

<Tabs type='vertical' >

  <Tab icon={<Icone/>} label='Produtos'>
    <div>Conteúdo do Produto </div>
  </Tab>
  
  <Tab  label='Compras'>
    <div>Conteúdo das Compras </div>
  </Tab>
  
   <Tab  label='Vendas' disabled>
    <div>Conteúdo das Vendas </div>
  </Tab>
  
</Tabs>
```

#### Tabs props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| value    | `number`                  | `false`  | -       | Índice da aba.      |
| onChange | `(value: number) => void` | `false`  | -       | Recebe novo índice. |
| type | `horizontal I vertical` | `false`  | horizontal     | - |

### Tabs.Tab props

| prop | tipo     | obrigatório | padrão | descrição |
| ---- | -------- | ----------- | ------ | --------- |
| icon    | `React.ReactNode`                  | `false`  | -       | -      |
| label | `string` | `true`  | -      | - |
| disabled | `boolean` | `false`  | -      | - |

**Comment by phelpa** [comment]
Eu acho que vou fazer o vertical um componente separado, já tá uma treta fazer o horizontal

**Comment by ffernandomoraes** [comment]
E aí querido, realmente é meio treta lidar com as duas direções. Mas como ficaria a implementação? Mesma coisa e só muda internamente o render do componente?

Acredito que precise ter um estado interno que controle a tab ativa (com isso é possível o usuário controlar quem começa "ativo").

E também acho que o componente deve ser controlled e uncontrolled (se passar a prop `<Tabs value='tab-1' />` ele é controlled, se não ele lida internamente quem está ativo e qual conteúdo exibir.

**Comment by phelpa** [comment]
Acho que vou fazer para a TabsVertical


```jsx
import TabsVertical from '@eduzz/houston-ui/Tabs/Vertical';
 const { Tab } = Tabs;

<TabsVertical >

  <Tab icon={<Icone/>} label='Produtos'>
    <div>Conteúdo do Produto </div>
  </Tab>
  
  <Tab  label='Compras'>
    <div>Conteúdo das Compras </div>
  </Tab>
  
   <Tab  label='Vendas' disabled>
    <div>Conteúdo das Vendas </div>
  </Tab>
  
</TabsVertical>
``
