### ISSUE TITLE
Erro ao tentar chamar o componente Alert.Action

### ISSUE THREAD

**Issue by MatheusRaj** [eduzz/houston#41]
Ao tentar usar o componente Actions acontece o seguinte erro: JSX element type 'Alert.Action' does not have any construct or call signatures.

![Screenshot_20210316_160606](https://user-images.githubusercontent.com/38676242/111365660-85412e80-8671-11eb-9773-02842815d80a.png)
![Screenshot_20210316_160633](https://user-images.githubusercontent.com/38676242/111365717-968a3b00-8671-11eb-92fd-50d4cfcd7ce1.png)

**Comment by ffernandomoraes** [comment]
Corrigido. A tipagem antiga estava dando erro.

![image](https://user-images.githubusercontent.com/22228470/111369668-1a462680-8676-11eb-9b81-066b2b0f268c.png)

**Comment by MatheusRaj** [comment]
Muito obrigado Fernando!
