### ISSUE TITLE
Componente : Accordion

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#417]
O que é : O accordion é um elemento de design que se expande no local para expor algumas informações ocultas.

Figma :  https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Desktop-components-handoff?node-id=3441%3A68923

![image](https://user-images.githubusercontent.com/17049866/185197541-25d0373f-74f9-45d0-a4f6-125c0ff9d902.png)

Em um primeiro momento pensei em deixar a api mais fechada, mas olhando o inventário do figma vejo que tem muitos casos a serem atendidos, então achei interessante em criar um **Accordion.Title** para deixar mais aberto (aceitando children) deixando na mão do dev para ele customizar(ver imagem abaixo), caso o usuário queira usar de forma simples (que nem na imagem acima) ele somente passaria um Typography e boa.

![image](https://user-images.githubusercontent.com/17049866/185197737-7382a3cf-7092-4180-86f2-8fa0899dee4c.png)

RFC : 

```jsx
import Accordion from '@eduzz/houston-ui/Accordion';

<Accordion>

  <Accordion.Item>

    <Accordion.Title>
       <Typography> Accordion Title</Typography>
     </Accordion.Title>
      <Accordion.Panel>
       <div>Conteúdo do Accordion</div>
    </Accordion.Panel>

  </Accordion.Item>
  
    <Accordion.Title>
       <Typography> Accordion Title2</Typography>
     </Accordion.Title>
      <Accordion.Panel>
       <div>Conteúdo do Accordion2</div>
    </Accordion.Panel>

  </Accordion.Item>
  
</Accordion>
```

#### Accordion props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| values    | `number[]`                  | `false`  | -       | Índices dos items que serão expandidos.      |
| onChange | `(value: number[]) => void` | `false`  | -       | Passa pelo callback os índices dos items que estão expandidos. |
| allowMultiple | `boolean` | `false`  | `false     | Se true mais que um item pode ser expandido  |

#### Accordion.Title props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| children    | `React.ReactNode`                  | `true`  | -       |      |

#### Accordion.Panel props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| children    | `React.ReactNode`                  | `true`  | -       | .      |

**Comment by phelpa** [comment]
Repensei várias coisas, vou abrir novamente depois

**Comment by miguelaugl** [comment]
Fala, mano, segue os pontos:

- Existem vezes que pode ter só um Accordion na tela, faz sentido ter esse componente Accordion que gerencia tudo? Eu acho que prefiro a abordagem do accordion ser responsável por si só e boa, ter a prop open ou expanded e o dev que controla, ai ele que decide se é múltiplo, se tem que fechar, etc;
- Sobre o Accordion.Title, por padrão você poderia renderizar um Typography estipulado pelo handoff e caso ele informe um ReactNode você renderizar só o ReactNode que ele passou.

**Comment by phelpa** [comment]
Cara realmente, acho que não tem porque fazer um componente paizão mesmo e gostei da ideia de renderizar o typography por padrão

Então ficaria 

```jsx
import Accordion from '@eduzz/houston-ui/Accordion';

<Accordion destroyOnClose open>
    <Accordion.Title>
        Título 
     </Accordion.Title>
      <Accordion.Panel>
       <div>Conteúdo do Accordion</div>
    </Accordion.Panel>
</Accordion>
```

Conforme conversamos : 

Por padrão se você abre o accordion ele vai 'guardar' o html, então quando você abrir o accordion novamente ele não vai renderizar novamente, mas se você não quiser isso você passa a prop destroyOnClose.


#### Accordion props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| onChange | `(value: boolean) => void` | `false`  | -       | . |
| open | `boolean` | `false`  | `false     | -  |
| destroyOnClose | `boolean` | `false`  | `false     | -  |



#### Accordion.Title props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| children    | `React.ReactNode`                  | `true`  | -       |      |

#### Accordion.Panel props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| children    | `React.ReactNode`                  | `true`  | -       | .      |

**Comment by miguelaugl** [comment]
Toopzera, vai na fé <3

**Comment by ffernandomoraes** [comment]
Cara, eu discordo de vocês. Pra mim o componente Accordion é dividido em dois componentes (ele mesmo e o Collapse). O Accordion trata-se de uma estrutura de informações (título com indicador se o conteúdo daquela seção está expandido e o conteúdo em si). E o Collapse que lida com a exibição ou não dos conteúdos.

Collapse (efeito de transição que pode ser usado em outros cenários):
```jsx
<Collapse visible={...} destroyOnClose={...} timeout={...}>
  ...
</Collapse>
```

Accordion (estrutura de informação que usa o Collapse para exibir/esconder o conteúdo):
```jsx
<Accordion open={[...]} destroyOnClose={...}>
  <Accordion.Item>
    <Accordion.Title disableTypography>...</Accordion.Title>
    <Accordion.Content>...</Accordion.Content> // ex: Panel, Content ...
  </Accordion.Item>

  <Accordion.Item>
    <Accordion.Title>...</Accordion.Title>
    <Accordion.Content>...</Accordion.Content>
  </Accordion.Item>

  <Accordion.Item>
    <Accordion.Title>...</Accordion.Title>
    <Accordion.Content>...</Accordion.Content>
  </Accordion.Item>
</Accordion>
```

Então resumindo, eu acredito que deva existir um componente pai para controlar os filhos. Pegando referências do mercado, Antd, Chakra UI, Boostrap React seguem essa estrutura ou algo parecido.
