### ISSUE TITLE
RFC  : Stepper

### ISSUE THREAD

**Issue by phelpa** [eduzz/houston#441]
O que é : O Stepper tem como objetivo mostrar ao usuário a quantidade de etapas dentro de um fluxo, bem como indicar qualquer etapa que está sendo apresentada.

Figma :  https://www.figma.com/file/WJWEph4jRV7uuVe4e9Pj13/Core-components-handoff?node-id=5200%3A103110

![image](https://user-images.githubusercontent.com/17049866/189724652-e18124ae-e6bd-424f-8911-99acec115902.png)

RFC : 

```jsx
import Stepper from '@eduzz/houston-ui/Stepper';

const [finished,setFinished] = useState([]) // finished = [0,1] se fosse a imagem acima

<Stepper finished={finished} onChange={finished=>setFinished(finished)} active={2}  > //opcionais
    <Step label='Básico'>
       <div>Conteúdo1</div>
    </Step>
  
    <Step label='Personalização' description='Personalize seu produto'>
       <div>Conteúdo2</div>
    </Step>

     <Step label='Comunicação' >
       <div>Conteúdo3</div>
    </Step>

    <Step label='Avançado' error>
       <div>Conteúdo3</div>
    </Step>
 
</Stepper>
```

Se o cara quiser o Stepper somente para se localizar na página (sem conteúdo) : 

```jsx
import Stepper from '@eduzz/houston-ui/Stepper';

const [finished,setFinished] = useState([]) // finished = [0,1] se fosse a imagem acima

<Stepper finished={finished} active={2}  > //opcionais
    <Step label='Básico'/>
    <Step label='Personalização' description='Personalize seu produto'/>
    <Step label='Comunicação' />
    <Step label='Avançado' error />
</Stepper>
```

#### Stepper props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| finished    | `number[]`                  | `false`  | -       | Índices dos Steps já finalizados.      |
| onChange | `(finished: number[]) => void` | `false`  | -       | Passa pelo callback os índices dos Steps já finalizados. |
| active | `number` | `false`  | `false     | Índice do Step ativo |
| children    | `React.ReactNode`                  | `true`  | -       |      |

#### Step props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| children    | `React.ReactNode`                  | `false`  | -       |      |
| error | `booolean` | `false`  | `false`     |  |
| label    | `string`                  | `true`  | -       |      |
| description    | `string`                  | `false`  | -       |      |

**Comment by ffernandomoraes** [comment]
Fala Pliniot, não seria mais fácil controlar os steppers concluídos por uma lógica mais simples? Por exemplo: `step 3` está ativo, podemos assumir que o `1` e o `2` estão concluídos. Sacou?

Eu pensaria em algo mais simples assim: 

#### Stepper props

| prop     | type                      | required | default | description         |
| -------- | ------------------------- | -------- | ------- | ------------------- |
| current    | `number`                  | `false`  | -       | -      |
| onChange | `(step: number, ev: 'next', 'prev') => void` | `false`  | -       | - |

Ou dá pra dividir em duas funções o `onChange`:  `onNext`, `onPrev`.

De resto, não tem muito segredo, o componente está bem simples =|

**Comment by ffernandomoraes** [comment]
Então, tem que validar isso com o designer, "Eu posso sair da etapa 3 e ir para 1 direto ou tenho que passar pela 2?".

Mas mesmo se for possível isso, da pra manter as mesmas props, não influencia em nada.
