### ISSUE TITLE
Página home da documentação oficial

### ISSUE THREAD

**Issue by joaopaulomoraes** [eduzz/houston#47]
Desenvolver a página home da documentação oficial (Docusaurus).

![image](https://user-images.githubusercontent.com/16243531/111831541-4d82f280-88ce-11eb-9c79-e115251b49ba.png)

**Comment by micheleambrosio** [comment]
Link do Figma do protótipo:
https://www.figma.com/file/8znoF6cZFGcYjtmNS056Q8/%40houston---homepage?node-id=1%3A2

**Comment by ffernandomoraes** [comment]
Muito bonito! Pra mim esta aprovado e pode começar a codar.
