### ISSUE TITLE
Componente: Switch

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#61]

**Comment by miguelaugl** [comment]
RFC:

```jsx
import Switch from '@eduzz/houston-ui/Switch';

<Switch checked defaultChecked size='small' onChange disabled />;
```

### Switch props available

| prop           | type                | required | default    | description |
| -------------- | ------------------- | -------- | ---------- | ----------- |
| checked        | `boolean`           | `false`  | `false`    | -           |
| defaultChecked | `boolean`           | `false`  | `false`    | -           |
| size           | `'small ou medium'` | `false`  | `'medium'` | -           |
| onChange       | `function`          | `false`  | -          | -           |
| disabled       | `boolean`           | `false`  | `false`    | -           |
