### ISSUE TITLE
Componente: WYSIWYG

### ISSUE THREAD

**Issue by ffernandomoraes** [eduzz/houston#62]

**Comment by danieloprado** [comment]
Esse vai dar trabalho hein kkk

**Comment by ffernandomoraes** [comment]
demais hahahha

**Comment by JonathasRodrigues** [comment]
hahaha bora, tem que virar referencia esse hein, pq os que tem ai disponiveis tão passando fome

**Comment by ffernandomoraes** [comment]
Abraça essa causa @JonathasRodrigues <3
